'use strict';

/**
 * @param {string} storageKey
 * @constructor
 */
const ActivityRepository = function(storageKey = 'Activities') {
  /** @type {Repository} */
  this.activities = new Repository(storageKey);

  this.activities._dataBacking = [
    {
      'title': 'Indiana Jones™ Adventure',
      'shortDescription': 'Embark on a fast-paced thrill ride in search of Indiana Jones—enter this cursed temple at your own risk!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-indiana-jones.jpg',
      'location': 'adventureland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Tarzan\'s Tree House',
      'shortDescription': 'Tour the legendary vine-swinger\'s jungle home—built in an 80-foot-tall tree—and experience life on the wild side.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-tarzan-tree.jpg',
      'location': 'adventureland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Jungle Cruise',
      'shortDescription': 'Cast off on a guided tour of the world\'s most remote rivers where adventure abounds—and the animals get the last laugh.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/adventureland-jungle-cruise.jpg',
      'location': 'adventureland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Walt Disney\'s Enchanted Tiki Room',
      'shortDescription': 'Tropical birds, tiki gods and colorful flowers come to life in a swinging South Seas musical celebration',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/adventureland-tiki-room.jpg',
      'location': 'adventureland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'The Tropical Hideaway',
      'shortDescription': 'Escape to an amazing jungle oasis offering fast \'n\'easy fare with a sense of adventure in the air!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-tropical-hidaway.jpg',
      'location': 'adventureland',
      'thrillLevel': '*',
    },
    {
      'title': 'Tropical Hideaway Merchandise Collection',
      'shortDescription': 'Welcome to our tropical hideaway where blue skies and gentle breezes never end - and summer is the ultimate escape from the everyday grind!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-tropical-hideaway-merch-collection.jpg',
      'location': 'adventureland',
      'thrillLevel': '*',
    },
    {
      'title': 'Bengal Barbecue',
      'shortDescription': 'Tear into some toothsome jungle skewers at this quick-service stand featuring spicy or sweet beef, chicken, bacon-wrapped asparagus or fresh vegetables.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-bengal.jpg',
      'location': 'adventureland',
      'thrillLevel': '*',
    },

    {
      'title': 'Splash Mountain',
      'shortDescription': 'Drop into a whimsical world filled with classic characters and songs on this thrilling log-flume adventure." --fun fact: exciting new Princess and the Frog refresh coming 2022',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-country-splash-mountain.jpg',
      'location': 'critter-country',
      'thrillLevel': 'HIGH',
    }, {
      'title': 'Davy Crockett\'s Explorer Canoes',
      'shortDescription': 'Paddle down the Rivers of America on a grand oar-venture all the way around Pirate’s Lair on Tom Sawyer Island.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-country-davy-crockett-canoes.jpg',
      'location': 'critter-country',
      'thrillLevel': 'MODERATE',
    }, {
      'title': 'The Many Adventures of Winnie the Pooh',
      'shortDescription': 'Buzz through Hundred-Acre Wood in an oversized beehive and revisit beloved songs and scenes from Winnie the Pooh.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-country-winnie-the-pooh.jpg',
      'location': 'critter-country',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'The Briar Patch',
      'shortDescription': 'Whether you\'re making your way up the mountain or stopping by after splashdown, hop on over to Critter Country, where you\'ll find a hideaway filled with all kinds of hats and caps!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/crittercounty-briar-patch.jpg',
      'location': 'critter-country',
      'thrillLevel': '*',
    },
    {
      'title': 'Pooh Corner',
      'shortDescription': 'Dip inside this hunny pot of a spot, where a candy kitchen awaits you, along with the finest merchandise from the Hundred-Acre Wood. You can also have your name written on Mickey ears or other headgear.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/crittercounty-pooh-corner.jpg',
      'location': 'critter-country',
      'thrillLevel': '*',
    },
    {
      'title': 'Hungry Bear Restaurant',
      'shortDescription': 'Forage for tasty food at this casual rustic eatery along the shore of Rivers of America.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-hungry-bear.jpg',
      'location': 'critter-country',
      'thrillLevel': '*',
    },

    {
      'title': 'Matterhorn Bobsleds',
      'shortDescription': 'Hurtle through a snow-capped mountain on a speeding alpine sled while avoiding the clutches of the Abominable Snowman',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-natterhorn.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Peter Pan\'s Flight',
      'shortDescription': 'Soar over London aboard an enchanted pirate ship to Never Land with the boy who wouldn’t grow up',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-peter-pan.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Casey Jr. Circus Train',
      'shortDescription': 'Enjoy a whimsical tour through miniature versions of fairytale locales from classic Disney movies',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-caseyjr-train.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Dumbo the Flying Elephant',
      'shortDescription': 'Enjoy a whimsical tour through miniature versions of fairytale locales from classic Disney movies.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-dumbo.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'It\'s a small world',
      'shortDescription': 'Board a whimsical boat ride for a song-filled journey around the globe—this cherubic chorus is pure joy!',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-small-world.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Mad Tea Party',
      'shortDescription': 'Pour yourself into an oversized teacup and spin through a whimsical party.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-teacup.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Pinocchio\'s Daring Journey',
      'shortDescription': 'Relive the classic adventures of the wooden puppet who dreamed of becoming a real boy',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-pinocchio.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Alice in Wonderland',
      'shortDescription': 'Take a topsy-turvy trip into the nonsensical world of Disney’s Alice in Wonderland aboard an oversized caterpillar.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-alice-in-wonder.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Mr. Toad\'s Wild Ride',
      'shortDescription': 'Zig and zag in a motorcar with J. Thaddeus Toad, Esq. on a manic drive through the countryside',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-mrtoad.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'King Arthur Carrousel',
      'shortDescription': 'Sit astride a regal steed at this classic attraction and gently “gallop” through a whirling backdrop of color and sound',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-carrousel.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Sleeping Beauty Castle Walkthrough',
      'shortDescription': 'Gaze at Sleeping Beauty Castle and venture inside to relive scenes from the beloved Disney classic',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-sleeping-beauty.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Snow White\'s Enchanted Wish',
      'shortDescription': 'Embark on a magical ride into memorable scenes from Snow White and the Seven Dwarfs.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-small-world.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Bibbidi Bobbidi Boutique',
      'shortDescription': 'Behold a royal transformation as kids become elegant princesses and shining knights—right before your eyes!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-bibbidi-botique.jpg',
      'location': 'fantasyland',
      'thrillLevel': '*',
    },
    {
      'title': 'Edelweiss Snacks',
      'shortDescription': 'Visit this alpine chalet where you’ll be happy to meet turkey legs, chimichangas and buttered corn on the cob. Then, chill out in the shadow of the Matterhorn with a fountain drink or frozen beverage in blue raspberry, cherry or apple.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-edelweiss-snacks.jpg',
      'location': 'fantasyland',
      'thrillLevel': '*',
    },

    {
      'title': 'Big Thunder Mountain',
      'shortDescription': 'Streak through a haunted gold mine aboard a speeding train on this thrilling coaster-style ride.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/frontierland-thunder-mountain.jpg',
      'location': 'frontierland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Pirate\'s Lair on Tom Sawyer Island',
      'shortDescription': 'Brave an adventure all your own at this secret island hideaway inspired by the stories of Mark Twain.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/frontierland-tom-sawyer.jpg',
      'location': 'frontierland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Sailing Ship Columbia',
      'shortDescription': 'Sail into the wilderness aboard a full-scale replica of a majestic ship from the 18th century.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/frontierland-columbia.jpg',
      'location': 'frontierland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Mark Twain Riverboat',
      'shortDescription': 'Cruise the scenic Rivers of America on a sightseeing tour aboard a majestic 19th-century paddle boat.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/frontierland-mark-twain.jpg',
      'location': 'frontierland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Pioneer Mercantile',
      'shortDescription': 'Hitch your ride just outside this Frontierland general store to get your fill of western wear, modern-day gear, gifts, knick-knacks and more.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/frontierland-pioneer-mechant.jpg',
      'location': 'frontierland',
      'thrillLevel': '*',
    },
    {
      'title': 'Westward Ho Trading Company',
      'shortDescription': 'Wheel your wagon over to this rustic Frontierland trading post where pins are WANTED! Reward yourself with an all-new pin collection or a limited-edition release—along with lanyards, accessories and more—before you ride off into the sunset.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/frontierland-westward-trading.jpg',
      'location': 'frontierland',
      'thrillLevel': '*',
    },
    {
      'title': 'Rancho del Zocalo Restaurante',
      'shortDescription': 'Round up all your amigos and head to the hacienda for classic Mexican cuisine on a muy bonita patio shaded with bougainvillea',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/frontierland-rancho.jpg',
      'location': 'frontierland',
      'thrillLevel': '*',
    },

    {
      'title': 'Gadget\'s Go Coaster',
      'shortDescription': 'Twist and turn on a speedy coaster ride built by the inventor mouse from Chip ‘n Dale Rescue Rangers.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/toontown-gadget-coaster.jpg',
      'location': 'toontown',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Roger Rabbit\'s Car Toon Spin',
      'shortDescription': 'Steer and spin a runaway taxicab through the wacky streets of Toontown as you follow the adventures of Roger Rabbit.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/toontown-roger-rabbit.jpg',
      'location': 'toontown',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Daisy\'s Diner',
      'shortDescription': 'Drop by this walk-up window for personal pizzas with your choice of cheese or pepperoni and cold beverages to wash ’em down. Get a soft drink-filled souvenir sipper cup for your little Daisy or Donald and sit outdoors by Toontown City Hall.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/toontown-daisys-diner.jpg',
      'location': 'toontown',
      'thrillLevel': '*',
    },
    {
      'title': 'Gag Factory',
      'shortDescription': 'Laugh with popular Disney friends as you search the topsy turvy world of Mickey\'s Toontown for the ultimate side-splitting souvenir.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/toontown-gag-factory.jpg',
      'location': 'toontown',
      'thrillLevel': '*',
    },

    {
      'title': 'The Disney Gallery',
      'shortDescription': 'See seasonal art exhibits showcasing attractions and icons from Disney parks around the world.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-disney-gallery.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Great Moments with Mr. Lincoln',
      'shortDescription': 'Revel in the stirring oratory of Abraham Lincoln—delivered in person—and explore rare Disneyland memorabilia.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/main-street-mr-lincoln.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Main Street Vehicles',
      'shortDescription': 'Travel back in time on a nostalgic ride down Main Street, U.S.A. in a charming turn-of-the-century vehicle.',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-vehicles.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Main Street Cinema',
      'shortDescription': 'Venture inside a vintage movie palace for a screening of some of Walt Disney’s earliest animated films.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-cinema.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Disneyland Railroad',
      'shortDescription': 'Embark on a relaxing 18-minute scenic journey aboard an authentic steam-powered train around Disneyland Park.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-disneyland-express.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Emporium',
      'shortDescription': 'Travel back through time as you enter a turn-of-the-century store offering the largest selection of souvenirs in all of Disneyland Park.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/mainstreet-emporium.jpg',
      'location': 'main-street',
      'thrillLevel': '*',
    },
    {
      'title': 'Plaza Inn',
      'shortDescription': 'Drop “inn” for hearty American fare the whole family will love.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/main-street-plaza-inn.jpg',
      'location': 'main-street',
      'thrillLevel': '*',
    },

    {
      'title': 'Pirates of the Caribbean',
      'shortDescription': 'Steer a course for the Golden Age of Piracy on a swashbuckling cruise through seas plagued by scoundrels',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/new-orleans-square-pirates-caribbean.jpg',
      'location': 'new-orleans-square',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Haunted Mansion',
      'shortDescription': 'Take your seat in a gloomy Doom Buggy for a spooky tour through this house of happy haunts.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/new-orleans-haunted-mansion.jpg',
      'location': 'new-orleans-square',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Cristal d\'Orleans',
      'shortDescription': 'Cut a groove through the bayou to come across exceptionally etched pieces of crystal. From personalized cups and pitchers to tiaras, figurines and more, celebrate the spirit of the New Orleans Square with a piece of glittering glassware!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/neworleans-cristal-dorleans.jpg',
      'location': 'new-orleans-square',
      'thrillLevel': '*',
    },
    {
      'title': 'Blue Bayou Restaurant',
      'shortDescription': 'Embark on a culinary adventure with Louisiana-inspired cuisine as you watch Pirates of the Caribbean boats glide past.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/new-orleans-blue-bayou.jpg',
      'location': 'new-orleans-square',
      'thrillLevel': '*',
    },

    {
      'title': 'Millennium Falcon: Smugglers Run',
      'shortDescription': 'Fly the Millennium Falcon on a thrilling interactive smuggling mission.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/star-wars-millenium-falcon.jpg',
      'location': 'star-wars',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Star Wars: Rise of the Resistance',
      'shortDescription': 'Join the Resistance in an epic battle against the First Order on this exciting new ride.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/star-wars-rise-resistance.jpg',
      'location': 'star-wars',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Black Spire Outfitters',
      'shortDescription': 'Outfit yourself for galactic adventures at the colorful apparel shop in \'Star Wars\': Galaxy\'s Edge.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/starwars-black-spire.jpg',
      'location': 'star-wars',
      'thrillLevel': '*',
    },
    {
      'title': 'Oga\'s Cantina',
      'shortDescription': 'Step inside this notorious local watering hole to partake of unique concoctions for all ages.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/star-wars-ogas-cantina.jpg',
      'location': 'star-wars',
      'thrillLevel': '*',
    },

    {
      'title': 'Star Tours - The Adventures Continues',
      'shortDescription': 'Make the jump to hyperspace aboard a 3D space flight to legendary destinations from the Star Wars saga',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-star-tours.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Space Mountain',
      'shortDescription': 'Race through the cosmos in the dark to the edge of the galaxy and back on a thrilling roller-coaster ride',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-space-mountain.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Star Wars Launch Bay',
      'shortDescription': 'Celebrate everything Star Wars at this headquarters for the epic space saga.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-launchbay.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Autopia',
      'shortDescription': 'Put the pedal to the metal for an unforgettable road trip along this amazing miniature roadway',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/tomorrowland-autopia.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Finding Nemo Submarine Voyage',
      'shortDescription': 'Journey into the charming world of Disney and Pixar’s Finding Nemo on a gentle undersea expedition.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-finding-nemo.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Buzz Lightyear Astro Blasters',
      'shortDescription': 'Fire lasers to defeat Zurg in this shooting-gallery attraction that puts you in the center of a thrilling space battle.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-buzz-lightyear-astro.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Astro Orbitor',
      'shortDescription': 'Pilot your very own rocket ship high in the sky amid a gleaming constellation of orbiting planets.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-astro-orbiter.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'The Star Trader',
      'shortDescription': 'Come in for a landing after your travels in a galaxy far, far away to find Star Wars-themed treasures and Disneyland merchandise.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-star-trader.jpg',
      'location': 'tomorrowland',
      'thrillLevel': '*',
    },
    {
      'title': 'Galactic Grill',
      'shortDescription': 'Fuel up for your next adventure at this space-themed eatery that serves out-of-this world selections for lunch and dinner',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-galactic-grill.jpg',
      'location': 'tomorrowland',
      'thrillLevel': '*',
    },
    {
      'title': 'Alien Pizza Planet',
      'shortDescription': 'Fuel up with out-of-this-world fast fare like breadsticks, pizza, and salad—it’s an Italiano meal you can’t refuse!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorowland-pizza-planet.jpg',
      'location': 'tomorrowland',
      'thrillLevel': '*',
    },

    {
      'title': 'OOOPS...Something went wrong.',
      'shortDescription': 'Hmmm....Looks like we don\'t have a ride to fit that description. Become an Imagineer and help up create one.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/404-image-1.jpg',
      'location': '404',
      'thrillLevel': '404',
    },
    {
      'title': 'OOOPS...Something went wrong.',
      'shortDescription': 'Hmmm....Looks like we don\'t have a ride to fit that description. Become an Imagineer and help up create one.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/404-image-2.jpg',
      'location': '404',
      'thrillLevel': '404',
    },
    {
      'title': 'OOOPS...Something went wrong.',
      'shortDescription': 'Hmmm....Looks like we don\'t have a ride to fit that description. Become an Imagineer and help up create one.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/404-image-3.jpg',
      'location': '404',
      'thrillLevel': '404',
    },
  ];
};