'use strict';

/**
 * @param {string} storageKey
 * @constructor
 */
const ActivityRepository = function(storageKey = 'Activities') {
  /** @type {Repository} */
  this.activities = new Repository(storageKey);

  this.activities._dataBacking = [
    {
      'title': 'Indiana Jones™ Adventure',
      'shortDescription': 'Embark on a fast-paced thrill ride in search of Indiana Jones—enter this cursed temple at your own risk!',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-indiana-jones.jpg',
      'location': 'adventureland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Tarzan\'s Tree House',
      'shortDescription': 'Tour the legendary vine-swinger\'s jungle home—built in an 80-foot-tall tree—and experience life on the wild side.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/adventureland-tarzan-tree.jpg',
      'location': 'adventureland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Jungle Cruise',
      'shortDescription': 'Cast off on a guided tour of the world\'s most remote rivers where adventure abounds—and the animals get the last laugh.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/adventureland-jungle-cruise.jpg',
      'location': 'adventureland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Walt Disney\'s Enchanted Tiki Room',
      'shortDescription': 'Tropical birds, tiki gods and colorful flowers come to life in a swinging South Seas musical celebration',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/adventureland-tiki-room.jpg',
      'location': 'adventureland',
      'thrillLevel': 'LOW',
    },

    {
      'title': 'Splash Mountain',
      'shortDescription': 'Drop into a whimsical world filled with classic characters and songs on this thrilling log-flume adventure." --fun fact: exciting new Princess and the Frog refresh coming 2022',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-country-splash-mountain.jpg',
      'location': 'critter-country',
      'thrillLevel': 'HIGH',
    }, {
      'title': 'Davy Crockett\'s Explorer Canoes',
      'shortDescription': 'Paddle down the Rivers of America on a grand oar-venture all the way around Pirate’s Lair on Tom Sawyer Island.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-country-davy-crockett-canoes.jpg',
      'location': 'critter-country',
      'thrillLevel': 'MODERATE',
    }, {
      'title': 'The Many Adventures of Winnie the Pooh',
      'shortDescription': 'Buzz through Hundred-Acre Wood in an oversized beehive and revisit beloved songs and scenes from Winnie the Pooh.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/critter-country-winnie-the-pooh.jpg',
      'location': 'critter-country',
      'thrillLevel': 'LOW',
    },

    {
      'title': 'Matterhorn Bobsleds',
      'shortDescription': 'Hurtle through a snow-capped mountain on a speeding alpine sled while avoiding the clutches of the Abominable Snowman',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-natterhorn.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Peter Pan\'s Flight',
      'shortDescription': 'Soar over London aboard an enchanted pirate ship to Never Land with the boy who wouldn’t grow up',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-peter-pan.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Casey Jr. Circus Train',
      'shortDescription': 'Enjoy a whimsical tour through miniature versions of fairytale locales from classic Disney movies',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-caseyjr-train.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Dumbo the Flying Elephant',
      'shortDescription': 'Enjoy a whimsical tour through miniature versions of fairytale locales from classic Disney movies.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-dumbo.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'It\'s a small world',
      'shortDescription': 'Board a whimsical boat ride for a song-filled journey around the globe—this cherubic chorus is pure joy!',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-small-world.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Mad Tea Party',
      'shortDescription': 'Pour yourself into an oversized teacup and spin through a whimsical party.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-teacup.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Pinocchio\'s Daring Journey',
      'shortDescription': 'Relive the classic adventures of the wooden puppet who dreamed of becoming a real boy',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-pinocchio.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Alice in Wonderland',
      'shortDescription': 'Take a topsy-turvy trip into the nonsensical world of Disney’s Alice in Wonderland aboard an oversized caterpillar.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-alice-in-wonder.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Mr. Toad\'s Wild Ride',
      'shortDescription': 'Zig and zag in a motorcar with J. Thaddeus Toad, Esq. on a manic drive through the countryside',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-mrtoad.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'King Arthur Carrousel',
      'shortDescription': 'Sit astride a regal steed at this classic attraction and gently “gallop” through a whirling backdrop of color and sound',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/fantasyland-carrousel.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Sleeping Beauty Castle Walkthrough',
      'shortDescription': 'Gaze at Sleeping Beauty Castle and venture inside to relive scenes from the beloved Disney classic',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-sleeping-beauty.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Snow White\'s Enchanted Wish',
      'shortDescription': 'Embark on a magical ride into memorable scenes from Snow White and the Seven Dwarfs.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/fantasyland-small-world.jpg',
      'location': 'fantasyland',
      'thrillLevel': 'LOW',
    },

    {
      'title': 'Big Thunder Mountain',
      'shortDescription': 'Streak through a haunted gold mine aboard a speeding train on this thrilling coaster-style ride.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/frontierland-thunder-mountain.jpg',
      'location': 'frontierland',
      'thrillLevel': 'HIGH',
    },

    {
      'title': 'Pirate\'s Lair on Tom Sawyer Island',
      'shortDescription': 'Brave an adventure all your own at this secret island hideaway inspired by the stories of Mark Twain.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/frontierland-tom-sawyer.jpg',
      'location': 'frontierland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Sailing Ship Columbia',
      'shortDescription': 'Sail into the wilderness aboard a full-scale replica of a majestic ship from the 18th century.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/frontierland-columbia.jpg',
      'location': 'frontierland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Mark Twain Riverboat',
      'shortDescription': 'Cruise the scenic Rivers of America on a sightseeing tour aboard a majestic 19th-century paddle boat.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/frontierland-mark-twain.jpg',
      'location': 'frontierland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Gadget\'s Go Coaster',
      'shortDescription': 'Twist and turn on a speedy coaster ride built by the inventor mouse from Chip ‘n Dale Rescue Rangers.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/toontown-gadget-coaster.jpg',
      'location': 'toontown',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Roger Rabbit\'s Car Toon Spin',
      'shortDescription': 'Steer and spin a runaway taxicab through the wacky streets of Toontown as you follow the adventures of Roger Rabbit.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/toontown-roger-rabbit.jpg',
      'location': 'toontown',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'The Disney Gallery',
      'shortDescription': 'See seasonal art exhibits showcasing attractions and icons from Disney parks around the world.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-disney-gallery.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },

    {
      'title': 'Great Moments with Mr. Lincoln',
      'shortDescription': 'Revel in the stirring oratory of Abraham Lincoln—delivered in person—and explore rare Disneyland memorabilia.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '',
      'imageUrl': 'img/main-street-mr-lincoln.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Main Street Vehicles',
      'shortDescription': 'Travel back in time on a nostalgic ride down Main Street, U.S.A. in a charming turn-of-the-century vehicle.',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-vehicles.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Main Street Cinema',
      'shortDescription': 'Venture inside a vintage movie palace for a screening of some of Walt Disney’s earliest animated films.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-cinema.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Disneyland Railroad',
      'shortDescription': 'Embark on a relaxing 18-minute scenic journey aboard an authentic steam-powered train around Disneyland Park.',
      'adaFriendly': 'ADA Friendly',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/main-street-disneyland-express.jpg',
      'location': 'main-street',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Pirates of the Caribbean',
      'shortDescription': 'Steer a course for the Golden Age of Piracy on a swashbuckling cruise through seas plagued by scoundrels',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/new-orleans-square-pirates-caribbean.jpg',
      'location': 'new-orleans-square',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Haunted Mansion',
      'shortDescription': 'Take your seat in a gloomy Doom Buggy for a spooky tour through this house of happy haunts.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/new-orleans-haunted-mansion.jpg',
      'location': 'new-orleans-square',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Millennium Falcon: Smugglers Run',
      'shortDescription': 'Fly the Millennium Falcon on a thrilling interactive smuggling mission.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/star-wars-millenium-falcon.jpg',
      'location': 'star-wars',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Star Wars: Rise of the Resistance',
      'shortDescription': 'Join the Resistance in an epic battle against the First Order on this exciting new ride.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/star-wars-rise-resistance.jpg',
      'location': 'star-wars',
      'thrillLevel': 'MODERATE',
    },

    {
      'title': 'Star Tours - The Adventures Continues',
      'shortDescription': 'Make the jump to hyperspace aboard a 3D space flight to legendary destinations from the Star Wars saga',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-star-tours.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Space Mountain',
      'shortDescription': 'Race through the cosmos in the dark to the edge of the galaxy and back on a thrilling roller-coaster ride',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-space-mountain.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'HIGH',
    },
    {
      'title': 'Star Wars Launch Bay',
      'shortDescription': 'Celebrate everything Star Wars at this headquarters for the epic space saga.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-launchbay.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Autopia',
      'shortDescription': 'Put the pedal to the metal for an unforgettable road trip along this amazing miniature roadway',
      'adaFriendly': '',
      'originalRide': '1955 Original Ride',
      'imageUrl': 'img/tomorrowland-autopia.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Finding Nemo Submarine Voyage',
      'shortDescription': 'Journey into the charming world of Disney and Pixar’s Finding Nemo on a gentle undersea expedition.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-finding-nemo.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'MODERATE',
    },
    {
      'title': 'Buzz Lightyear Astro Blasters',
      'shortDescription': 'Fire lasers to defeat Zurg in this shooting-gallery attraction that puts you in the center of a thrilling space battle.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-buzz-lightyear-astro.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'LOW',
    },
    {
      'title': 'Astro Orbitor',
      'shortDescription': 'Pilot your very own rocket ship high in the sky amid a gleaming constellation of orbiting planets.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/tomorrowland-astro-orbiter.jpg',
      'location': 'tomorrowland',
      'thrillLevel': 'MODERATE',
    },

    {
      'title': 'OOOPS...Something when wrong.',
      'shortDescription': 'Hmmm....Looks like we don\'t have a ride to fit that description. Become an Imagineer and help up create one.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/404-image-1.jpg',
      'location': '404',
      'thrillLevel': '404',
    },
    {
      'title': 'OOOPS...Something when wrong.',
      'shortDescription': 'Hmmm....Looks like we don\'t have a ride to fit that description. Become an Imagineer and help up create one.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/404-image-2.jpg',
      'location': '404',
      'thrillLevel': '404',
    },
    {
      'title': 'OOOPS...Something when wrong.',
      'shortDescription': 'Hmmm....Looks like we don\'t have a ride to fit that description. Become an Imagineer and help up create one.',
      'adaFriendly': '',
      'originalRide': '',
      'imageUrl': 'img/404-image-3.jpg',
      'location': '404',
      'thrillLevel': '404',
    },
  ];
};